apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: sitecore-xm1-mssql-init
  newName: sitecondockerk8sdemo.azurecr.io/xm1/sitecore-horizon-integration-xm1-mssql-init #scr.sitecore.com/sxp/sitecore-xm1-mssql-init
  newTag: latest #10.1-ltsc2019
- name: sitecore-xm1-solr-init
  newName: scr.sitecore.com/sxp/sitecore-xm1-solr-init
  newTag: 10.1-ltsc2019
resources:
- mssql-init.yaml
- solr-init.yaml
