apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../../k8s-sitecore-xm1/ingress-nginx

patchesJson6902:
  - path: patch-ingress.json
    target:
      group: extensions
      kind: Ingress
      name: sitecondocker-ingress
      version: v1beta1